### ISSUE TITLE
Missing out/ directory

### ISSUE THREAD

**Issue by jpaczia** [open-vsx/publish-extensions#163]
Currently the [LaTex-Workshop](https://github.com/James-Yu/LaTeX-Workshop) extension is not working in VSCodium.
According to [this](https://github.com/James-Yu/LaTeX-Workshop/issues/2160#issuecomment-652137338) comment the `out/` of OpenVSX directory is missing.
The issue has already been reported to the VSCodium team [here](https://github.com/VSCodium/vscodium/issues/486#issuecomment-697735141) but has been rejected.

**Comment by spoenemann** [comment]
Let's see if the change fixes the issue (extensions are deployed once per day). If yes, I can remove the old broken versions.

**Comment by spoenemann** [comment]
@jpaczia could you check the latest version 8.13.2?
https://open-vsx.org/extension/James-Yu/latex-workshop

**Comment by jpaczia** [comment]
Thanks, it's working again :+1:

**Comment by spoenemann** [comment]
I deleted the broken versions.

**Comment by mseri** [comment]
Version 8.20.2 is failing again with the same error for me

**Comment by l1ving** [comment]
I thought I was the only one. 

Dev tools log:
```
workbench.desktop.main.js:2036 Activating extension 'James-Yu.latex-workshop' failed: Cannot find module '/home/liv/.vscode-oss/extensions/james-yu.latex-workshop-8.20.2/out/src/main.js'
Require stack:
- /usr/share/vscodium-bin/resources/app/out/vs/loader.js
- /usr/share/vscodium-bin/resources/app/out/bootstrap-amd.js
- /usr/share/vscodium-bin/resources/app/out/bootstrap-fork.js.
```

**Comment by l1ving** [comment]
This issue is being tracked at #414, and has been resolved (mostly).

**Comment by RB-Lab** [comment]
Hi! Looks like a similar issue is in `template-string-converter` package: https://github.com/meganrogge/template-string-converter/issues/59 Could it be related (e.g. common publishing pipeline)?

**Comment by akosyakov** [comment]
Could you open a new issue if `template-string-converter` does not work?

**Comment by RB-Lab** [comment]
Sure, NP.

**Comment by filiptronicek** [comment]
It looks like the extension is still not working, but because of another cause, created https://github.com/James-Yu/LaTeX-Workshop/issues/3011 to track this.

**Comment by filiptronicek** [comment]
Apparently this will take a while to fix: https://github.com/James-Yu/LaTeX-Workshop/issues/3011#issuecomment-992627030
